// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearScanHistory() {
  return window['go']['main']['App']['ClearScanHistory']();
}

export function ConfigureScanner(arg1) {
  return window['go']['main']['App']['ConfigureScanner'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function LightGBMModelStatus() {
  return window['go']['main']['App']['LightGBMModelStatus']();
}

export function LoadLightGBMModel(arg1) {
  return window['go']['main']['App']['LoadLightGBMModel'](arg1);
}

export function PickLightGBMModelFile() {
  return window['go']['main']['App']['PickLightGBMModelFile']();
}

export function PickScanDirectory() {
  return window['go']['main']['App']['PickScanDirectory']();
}

export function PickScanFiles() {
  return window['go']['main']['App']['PickScanFiles']();
}

export function PredictFileLightGBM(arg1, arg2) {
  return window['go']['main']['App']['PredictFileLightGBM'](arg1, arg2);
}

export function PredictLightGBM(arg1) {
  return window['go']['main']['App']['PredictLightGBM'](arg1);
}

export function QuarantineFiles(arg1) {
  return window['go']['main']['App']['QuarantineFiles'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function ScanFiles(arg1) {
  return window['go']['main']['App']['ScanFiles'](arg1);
}

export function ScanFilesLightGBM(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScanFilesLightGBM'](arg1, arg2, arg3);
}

export function UnloadLightGBMModel() {
  return window['go']['main']['App']['UnloadLightGBMModel']();
}
