// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearScanHistory():Promise<void>;

export function ConfigureScanner(arg1:main.ScannerModelPaths):Promise<void>;

export function DeleteHistory(arg1:Array<number>):Promise<void>;

export function GetAppConfig():Promise<main.AppConfigDTO>;

export function GetHistory(arg1:number):Promise<Array<main.ScanHistoryRow>>;

export function LightGBMModelStatus():Promise<main.LightGBMModelStatus>;

export function LoadLightGBMModel(arg1:string):Promise<void>;

export function PickLightGBMModelFile():Promise<string>;

export function PickScanDirectory():Promise<Array<string>>;

export function PickScanFiles():Promise<Array<string>>;

export function PredictFileLightGBM(arg1:string,arg2:boolean):Promise<number>;

export function PredictLightGBM(arg1:Array<number>):Promise<number>;

export function QuarantineFiles(arg1:Array<string>):Promise<number>;

export function SaveAppConfig(arg1:main.AppConfigDTO):Promise<void>;

export function SaveHistory(arg1:Array<main.HistorySaveEntry>):Promise<void>;

export function ScanFiles(arg1:Array<string>):Promise<Array<main.FileScoreResult>>;

export function ScanFilesLightGBM(arg1:string,arg2:Array<string>,arg3:boolean):Promise<Array<main.FileScoreResult>>;

export function UnloadLightGBMModel():Promise<void>;
